title: Workshop at archmetalDBM
author:
  name: GlobaLID Core Team
  email: globalid@bergbaumuseum.de
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

theme: minima

header_pages:
 - about.md

#social_links:
#  github: archmetalDBM

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

plugins:
 - jekyll-feed

  

